### PR TITLE
[WIP] Deploy to cloud.gov

### LINKED ISSUE #33: Deploy app-in-progress to cloud.gov
- [ ] Finalize URL
- [ ] Deployment scripts or documentation
- [ ] Enables ATO activities
  - [ ] Monitoring
  - [ ] Dynamic scanning

### PR DESCRIPTION
**Pull request by fureigh**
Definition of done: fixes #33. :)

Steps to reproduce current state:
1. `cd` to the root directory of this repo.
2. `cf push ffd-info-exchange-fafsa`
3. Observe as you eventually get this/these "line 4"-related error(s):

```
-----> Downloaded app package (1.9M)
-----> Downloaded app buildpack cache (37M)
/var/vcap/data/dea_next/admin_buildpacks/a12a1517-f676-4c7a-aa6c-1b05887190f3_cf94e0af33ae6249404d935c33c2d139f4585195/bin/detect: line 4: dirname /var/vcap/data/dea_next/admin_buildpacks/a12a1517-f676-4c7a-aa6c-1b05887190f3_cf94e0af33ae6249404d935c33c2d139f4585195/bin/detect: No such file or directory
/var/vcap/data/dea_next/admin_buildpacks/a12a1517-f676-4c7a-aa6c-1b05887190f3_cf94e0af33ae6249404d935c33c2d139f4585195/bin/detect: line 4: dirname : command not found
-------> Buildpack version 1.5.10
-----> Found python-2.7.12, removing
-----> Installing python-3.5.1
```

### CODE REVIEW

**Comment by fureigh** [comment]
@porta-antiporta 
tag-youre-it

**Comment by porta-antiporta** [comment]
@fureigh some progress:  

Our current build for some reason is not detecting that it should use the python buildpack.  As such it is defaulting to looking for a [custom buildpack](https://docs.cloudfoundry.org/buildpacks/custom.html#detect-script) which needs that `\bin\detect` file. 

So when I force it to use the [python buildpack](https://docs.cloudfoundry.org/buildpacks/python/index.html) by appending `-b https://github.com/cloudfoundry/buildpack-python.git` to the `cf push` command it gets past that error but the app still fails to start. 

Sample output:

```
cf push porta-fafsa -b https://github.com/cloudfoundry/buildpack-python.git
Using manifest file /Users/michaelantiporta/documents/ffd-info-exchange/manifest.yml

Updating app porta-fafsa in org sandbox-gsa / space michael.antiporta as michael.antiporta@gsa.gov...
OK

Uploading porta-fafsa...
Uploading app files from: /Users/michaelantiporta/documents/ffd-info-exchange
Uploading 1.3M, 149 files
Done uploading               
OK

Stopping app porta-fafsa in org sandbox-gsa / space michael.antiporta as michael.antiporta@gsa.gov...
OK

Starting app porta-fafsa in org sandbox-gsa / space michael.antiporta as michael.antiporta@gsa.gov...
-----> Downloaded app package (1.9M)
-----> Downloaded app buildpack cache (49M)
Cloning into '/tmp/buildpacks/buildpack-python'...
Submodule 'compile-extensions' (https://github.com/cloudfoundry/compile-extensions.git) registered for path 'compile-extensions'
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out '40e9d1571821b1858112ec30fd8ad587bcf9b3af'
-------> Buildpack version 1.5.11
     $ pip install -r requirements.txt
     $ python ffd_info_exchange/manage.py collectstatic --noinput
       214 static files copied to '/home/vcap/app/ffd_info_exchange/staticfiles', 214 post-processed.
-----> Uploading droplet (57M)

0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
FAILED
Start app timeout

TIP: Application must be listening on the right port. Instead of hard coding the port, use the $PORT environment variable.

Use 'cf logs porta-fafsa --recent' for more information
```

**Comment by fureigh** [comment]
@porta-antiporta Interesting... what happens when you run `cf logs porta-fafsa --recent`?

**Comment by porta-antiporta** [comment]
sending you the full log file @fureigh in email/gdrive.  Lot of timeout errors, but I _think_ this is the problem:

2016-10-27T15:30:05.18-0500 [App/0]      ERR Error: Malformed application 'ffd-info-exchange-fafsa.wsgi:application'

**Comment by porta-antiporta** [comment]
full error log file located [here](https://docs.google.com/document/d/17eDS-fHVX_9ecKA_uctFBqj4yqbkP-R-biAFnHUTn1E/edit)

**Comment by fureigh** [comment]
@porta-antiporta Ah, thanks. Hang on — I'll delete the one I started so you can just push without having to use a new app name everywhere.

**Comment by porta-antiporta** [comment]
Have to tap out for the day; unfortunately was unable to make more progress.

However from:

http://stackoverflow.com/questions/22821597/waitress-on-heroku-giving-error
http://docs.pylonsproject.org/projects/waitress/en/latest/runner.html

It _seems_ the `Procfile` should not be have `fafsa` in it; as that is supposed to be formatted so that it can find the `wsgi.py` file.  

But... also ¯_(ツ)_/¯

**Comment by fureigh** [comment]
Passing this to @donjo per #33.

**Comment by fureigh** [comment]
@donjo Safe to close this one as `wontfix`, right?

**Comment by donjo** [comment]
word

**Pull request closed without merging**
