### PR TITLE
Radio and Checkbox button rendering

### PR DESCRIPTION
**Pull request by donjo**
This PR is to fix the radio button and checkboxes to ensure they are utilizing the USWDS styles. 

So far they render correctly but will need additional work to remove the list style being applied to them and adjust spacing and indentation. 

Also the rest of the form fields will eventually need converted to the newly created widget templates `UswdsRadioSelect` and `UswdsCheckbox`

thank you 18F/calc team for some tips!

### CODE REVIEW

**Comment by fureigh** [comment]
Thanks, @donjo! I'll run with this for a bit.

**Comment by fureigh** [comment]
Confirming: after the commits I just added, all radio button and checkbox fields now use the appropriate USWDS widgets.

The remaining steps are to:
* [ ] Add the `usa-unstyled-list` class to the `ul` elements.
* [ ] Determine which USWDS class(es) or elements will automatically implement appropriate spacing. If none, implement manually.

**Comment by donjo** [comment]
Since we know the structure of this form and all its permutations (we already have all the content loaded) I elected to just use child combinators to style the selects and checkboxes.  Obviously the ideal solution would be for me to learn more python and figure out how to break apart the widget template and apply the appropriate USWDS classes to these items but maybe the 10 minute fix is sufficient. 

If the implementation of the optional service forms breaks this we can always roll it back and look further into how to do it in a more sustainable way. 

screen shot 2016-12-12 at 12 24 30 pm

**Comment by fureigh** [comment]
Thanks for the info, @donjo! I made a follow-up ticket at #137 for that possible refactoring; will look into it next week as time allows. Given the circumstances, despite the feeling technical debt gives me in the pit of my stomach, I agree that this is a reasonable approach. :shipit:

**Review by fureigh — APPROVED** [review]
(See above.)

**Pull request merged**
