### PR TITLE
Update asset handling

### PR DESCRIPTION
**Pull request by fureigh**
This PR:
- makes the flag icon load correctly (follow-up on #46) and
- creates a future home for [custom stylesheets](https://docs.djangoproject.com/en/1.10/howto/static-files/) and the like.

Part of #26.

### CODE REVIEW

**Comment by fureigh** [comment]
Whoops — gotta fix one thing.

**Comment by fureigh** [comment]
Fixed USWDS handling (thanks, @donjo) and also removed the usa.gov logo, as it's not in use.

**Review by donjo — APPROVED** [review]
👍

**Comment by fureigh** [comment]
@donjo GitHub says you approved this, but merging is still blocked (`At least one approved review is required by reviewers with write access.`). Do you see anything else to do here?

**Comment by fureigh** [comment]
@donjo Must've been a refresh error; as soon as I posted that comment, I got a green light. All good.

**Pull request merged**
